import os
from typing import Optional


def generate_stubs(
    name: str, library_type: str, out_path: Optional[str] = None
) -> str:
    """
    Generates a Python PEP 484 type stub (.pyi) file for a registered dynamic library or WASM module,
    providing full IDE autocompletion and hover documentation for all dynamic exports.

    Args:
        name: The registered name of the dynamic library or WASM module.
        library_type: Either 'dylib' or 'wasm'.
        out_path: Optional output file path. Defaults to '{name}_proxy.pyi' in the current directory.

    Returns:
        The absolute path to the generated type stub file.
    """
    if library_type.lower() == "wasm":
        from ._pyroxide import get_wasm_exports

        exports = get_wasm_exports(name)
        class_name = f"{name.capitalize()}WasmProxy"
        factory_name = f"load_wasm_{name}"
    elif library_type.lower() == "dylib":
        from ._pyroxide import get_dylib_exports

        exports = get_dylib_exports(name)
        class_name = f"{name.capitalize()}DylibProxy"
        factory_name = f"load_dylib_{name}"
    else:
        raise ValueError("library_type must be either 'wasm' or 'dylib'")

    if not out_path:
        out_path = f"{name}_proxy.pyi"

    lines = [
        "# Auto-generated by Pyroxide. Do not edit directly.",
        "from typing import Any",
        "from pyroxide import TaskHandle",
        "",
        f"class {class_name}:",
        "    \"\"\"",
        f"    Type-annotated proxy for registered {library_type} module '{name}'.",
        "    \"\"\"",
    ]

    if not exports:
        lines.append("    pass")
    else:
        for symbol in exports:
            # Generate generic typed signature
            lines.append(f"    def {symbol}(self, payload: Any) -> TaskHandle: ...")

    lines.append("")
    # Add a typed factory helper or hint
    lines.append(f"def {factory_name}(isolated: bool = ...) -> {class_name}: ...")

    content = "\n".join(lines) + "\n"
    with open(out_path, "w") as f:
        f.write(content)

    return os.path.abspath(out_path)
