import os
from typing import Optional


def generate_stubs(name: str, library_type: str, out_path: Optional[str] = None) -> str:
    """
    Generates a Python PEP 484 type stub (.pyi) file for a registered dynamic library or WASM module,
    providing full IDE autocompletion and hover documentation for all dynamic exports.

    Args:
        name: The registered name of the dynamic library or WASM module.
        library_type: Either 'dylib' or 'wasm'.
        out_path: Optional output file path. Defaults to '{name}_proxy.pyi' in the current directory.

    Returns:
        The absolute path to the generated type stub file.
    """
    sigs = {}
    if library_type.lower() == "wasm":
        from ._pyroxide import get_wasm_exports

        exports = get_wasm_exports(name)
        class_name = f"{name.capitalize()}WasmProxy"
        factory_name = f"load_wasm_{name}"
    elif library_type.lower() == "dylib":
        from ._pyroxide import get_dylib_exports, get_dylib_metadata

        exports = get_dylib_exports(name)
        class_name = f"{name.capitalize()}DylibProxy"
        factory_name = f"load_dylib_{name}"

        # Discover FFI signatures from metadata
        metadata_str = get_dylib_metadata(name)
        if metadata_str:
            for entry in metadata_str.split(";"):
                if not entry:
                    continue
                func_parts = entry.split(":")
                if len(func_parts) == 2:
                    func_name, sig_part = func_parts
                    sig_parts = sig_part.split("|")
                    if len(sig_parts) == 2:
                        args_part, ret_type = sig_parts
                        args = [a for a in args_part.split(",") if a]
                        sigs[func_name] = args
    else:
        raise ValueError("library_type must be either 'wasm' or 'dylib'")

    # Print compile-time warnings for potential memory leaks if pyroxide_plugin_free is missing for raw tasks
    if library_type.lower() == "dylib" and "pyroxide_plugin_free" not in exports:
        raw_funcs = [
            s
            for s in exports
            if s not in ("pyroxide_metadata", "pyroxide_plugin_free") and s not in sigs
        ]
        if raw_funcs:
            import sys

            print(
                f"⚠️  Warning: Library '{name}' exposes raw binary tasks {raw_funcs} but "
                f"does not export 'pyroxide_plugin_free'. Memory leaks will occur "
                f"if these functions return heap-allocated pointers.",
                file=sys.stderr,
            )

    if not out_path:
        out_path = f"{name}_proxy.pyi"

    lines = [
        "# Auto-generated by Pyroxide. Do not edit directly.",
        "from typing import Any",
        "from pyroxide import TaskHandle",
        "",
        f"class {class_name}:",
        '    """',
        f"    Type-annotated proxy for registered {library_type} module '{name}'.",
        '    """',
    ]

    if not exports:
        lines.append("    pass")
    else:
        for symbol in exports:
            if symbol in sigs:
                arg_list = [f"arg{i}: Any" for i in range(len(sigs[symbol]))]
                args_str = ", ".join(arg_list)
                if args_str:
                    lines.append(
                        f"    def {symbol}(self, {args_str}) -> TaskHandle: ..."
                    )
                else:
                    lines.append(f"    def {symbol}(self) -> TaskHandle: ...")
            else:
                lines.append(f"    def {symbol}(self, payload: Any) -> TaskHandle: ...")

    lines.append("")
    # Add a typed factory helper or hint
    lines.append(f"def {factory_name}(isolated: bool = ...) -> {class_name}: ...")

    content = "\n".join(lines) + "\n"
    with open(out_path, "w") as f:
        f.write(content)

    # Write runtime .py helper file alongside the stub to prevent ModuleNotFoundError
    py_path = os.path.splitext(out_path)[0] + ".py"
    if library_type.lower() == "wasm":
        py_lines = [
            "# Auto-generated by Pyroxide. Do not edit directly.",
            "from pyroxide.wasm import load_wasm, WasmProxy",
            "",
            f"class {class_name}(WasmProxy):",
            "    def __init__(self, isolated: bool = False):",
            f'        super().__init__("{name}", isolated=isolated)',
            "",
            f"def {factory_name}(isolated: bool = False) -> {class_name}:",
            f'    return load_wasm("{name}", isolated=isolated)',
        ]
    else:
        py_lines = [
            "# Auto-generated by Pyroxide. Do not edit directly.",
            "from pyroxide.plugins import load_dylib, DylibProxy",
            "",
            f"class {class_name}(DylibProxy):",
            "    def __init__(self, isolated: bool = False):",
            f'        super().__init__("{name}", isolated=isolated)',
            "",
            f"def {factory_name}(isolated: bool = False) -> {class_name}:",
            f'    return load_dylib("{name}", isolated=isolated)',
        ]

    py_content = "\n".join(py_lines) + "\n"
    with open(py_path, "w") as f:
        f.write(py_content)

    return os.path.abspath(out_path)
